development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rTracker_dev
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rTracker_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rTracker_prod
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
